### ISSUE TITLE
emmc does not get flashed

### ISSUE THREAD

**Issue by richardlevano** [balena-os/balena-variscite#70]
I have followed the steps described here 
https://www.balena.io/os/docs/custom-build/#supporting-your-own-board
to build from scratch the "imx6ul-var-dart" image

After setup the yocto build environment and needed software :

I successfully generate the image (2.7Gb) but after booting the image from sdcard in the Dart 6UL base board with switches set to boot from sd card I get :  

`U-Boot SPL 2017.03-mx6ul+g466898df53 (Dec 09 2018 - 15:15:41)

Part number: VSM-6UL-A06B
Assembly: AS1811141870
Date of production: 2018 Nov 20
DART-6UL-5G configuration: eMMC WiFi
Trying to boot from MMC1
MMC Boot Device: mmc0 (SD)

U-Boot 2017.03-mx6ul+g466898df53 (Dec 09 2018 - 15:15:41 +0000)

CPU:   Freescale i.MX6ULL rev1.1 900 MHz (running at 396 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 29C
Reset cause: POR
Board: Variscite DART-6UL
I2C:   ready
DRAM:  512 MiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
*** Warning - bad CRC, using default environment

Display: VAR-WVGA-LCD (800x480)
Video: 800x480x24
Error (-1): cannot determine file size
In:    serial
Out:   serial
Err:   serial
switch to partitions #0, OK
mmc0 is current device
eMMC:  7.3 GiB
Net:   got MAC0 address from fuse: f8:dc:7a:22:53:7e
FEC0 [PRIME], usb_ether
Error: usb_ether address not set.

Normal Boot
Hit any key to stop autoboot:  0 
Scanning MMC and USB devices 0 1 2
reading resin-image-flasher
24 bytes read in 14 ms (1000 Bytes/s)
Found resin flasher on mmc 0
Loading resinOS_uEnv.txt from mmc device 0 partition 1
reading resinOS_uEnv.txt
** Unable to read file resinOS_uEnv.txt **
switch to partitions #0, OK
mmc0 is current device
switch to partitions #0, OK
mmc0 is current device
reading /uEnv.txt
** Unable to read file /uEnv.txt **
reading /boot.scr
** Unable to read file /boot.scr **
reading /zImage
10821312 bytes read in 493 ms (20.9 MiB/s)
Booting from mmc ...
fdt_file=imx6ull-var-dart-sd_emmc.dtb
reading /imx6ull-var-dart-sd_emmc.dtb
** Unable to read file /imx6ull-var-dart-sd_emmc.dtb **

Starting kernel ...
`

**Something goes wrong and the emmc memory is not flashed with the balenaOS.
Does somebody has a clue that what might  be the problem?

If I use the sd card image from "variscite" the manufacturer I am able to flash in the emmc either Debian or Yocto with no problems at all.

Thanks**

**Comment by richardlevano** [comment]
I have built v2.28.0 and I confirm the Dart 6UL emmc gets flashed.
After I reboot from emmc the BalenaOS logo is displayed in the LCD of the dev kit.
eth0 is up but wlan0 is down despite being set. I will have to investigate.

Thanks for your help.

**Comment by richardlevano** [comment]
I have followed :  
https://www.balena.io/open/docs/getting-started/#Installing-the-CLI-Client

And I able to set the wifi configuration into the balenaOS image.
After reboot the wlan0 gets up.

**Comment by 0ohm** [comment]
Sorry, but i have the same issue and i cant build. Bitbake server error. Anyone have the .img?

**Comment by floion** [comment]
@0ohm for what board is this? imx6 var dart board?

**Comment by 0ohm** [comment]
@floion dart-6ul with emmc

**Comment by floion** [comment]
@0ohm what OS version are you using? Is it downloaded from the balena dashboard?
