### ISSUE TITLE
variscite Dart 6UL imx6ul v2.29.2 Rev4 LCD

### ISSUE THREAD

**Issue by richardlevano** [balena-os/balena-variscite#90]
How to use the LCD in an Application running  balena-variscite for dart 6ul v2.29.2 Rev4 ?

Any hints?

**Comment by floion** [comment]
Hi, we haven't used an LCD on our side.
What are the symptoms? Did you connect an LCD screen and nothing appears when you boot?
Can you detail the setup? What LCD screen, how it is connected etc?

**Comment by richardlevano** [comment]
Hi @floion,

Thank for yor interest on this post.

I am using variscite Dart 6ul official delelopment kit.
https://www.variscite.com/products/evaluation-kits/dart-6ul-kits/

The host runs BalenaOS v2.29.2 rev4 and the balena application runs on a https://hub.docker.com/r/balenalib/imx6ul-var-dart-python.    
container.

The lcd shows the balena logo at boot time but then when the balena app starts nothings show in the lcd. Eventually the lcd goes to sleep.

I am using electron in the balena app. My guess is that probably I need to install the x.org (x windows) libraries to do a "starx" together with probably some lcd drivers from variscite but I could not find any guide or related info online to get me started.

**Comment by floion** [comment]
Did you already test with one of the examples? For example https://github.com/balena-io/resin-electronjs ?

**Comment by richardlevano** [comment]
No I have not.
I will try and let you know.
Is this example hardware agnostic?
Or targets to Rasperry Pi?

**Comment by floion** [comment]
Should work for all hardware

**Comment by richardlevano** [comment]
Sounds good.
 I will try today and let you know outcome.

**Comment by richardlevano** [comment]
Unfortunately did not work.
Looks like the repo is heavily based on RPI architecture :disappointed: 
The logo appears at booting but no electron app is displayed after.

**Comment by floion** [comment]
Hi, I tried on my side and was able to see the unicorn displayed by the app I mentioned earlier.
What exactly didn't work when you tested it? The repo is not tied to RPI at all

**Comment by floion** [comment]
@richardlevano can this be closed now?
